name: DontForget
options:
  bundleIdPrefix: com.yuxuan
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"
  DEVELOPMENT_TEAM: ""
  
targets:
  DontForget:
    type: application
    platform: iOS
    sources:
      - DontForget
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.yuxuan.dontforget
      INFOPLIST_FILE: DontForget/Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      SWIFT_VERSION: "5.9"
    info:
      path: DontForget/Info.plist
      properties:
        CFBundleDisplayName: Don't Forget
        CFBundleShortVersionString: "1.0.0"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSLocationWhenInUseUsageDescription: "We need your location to remind you when you're near places you've saved."
        NSLocationAlwaysAndWhenInUseUsageDescription: "Allow location access to get reminders even when the app is closed."
        UIBackgroundModes:
          - location
